/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapEnDotxmlRouteImport } from './routes/sitemap-en[.]xml'
import { Route as SitemapArDotxmlRouteImport } from './routes/sitemap-ar[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as GovernoratesSlugRouteImport } from './routes/governorates.$slug'
import { Route as DownloadsSlugRouteImport } from './routes/downloads.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as PreviewPagesSlugRouteImport } from './routes/preview.pages.$slug'
import { Route as PreviewKnowledgeSlugRouteImport } from './routes/preview.knowledge.$slug'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTranslationsRouteImport } from './routes/_authenticated/admin.translations'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'
import { Route as AuthenticatedAdminSocialCacheRouteImport } from './routes/_authenticated/admin.social-cache'
import { Route as AuthenticatedAdminSettingsKeysRouteImport } from './routes/_authenticated/admin.settings-keys'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminQaReportsRouteImport } from './routes/_authenticated/admin.qa-reports'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin.newsletter'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminLegalRouteImport } from './routes/_authenticated/admin.legal'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminKpiRouteImport } from './routes/_authenticated/admin.kpi'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminHeroSlidesRouteImport } from './routes/_authenticated/admin.hero-slides'
import { Route as AuthenticatedAdminGovernoratesRouteImport } from './routes/_authenticated/admin.governorates'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin.faqs'
import { Route as AuthenticatedAdminDownloadsAnalyticsRouteImport } from './routes/_authenticated/admin.downloads-analytics'
import { Route as AuthenticatedAdminDownloadsRouteImport } from './routes/_authenticated/admin.downloads'
import { Route as AuthenticatedAdminDownloadLeadsRouteImport } from './routes/_authenticated/admin.download-leads'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminCareersRouteImport } from './routes/_authenticated/admin.careers'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as AuthenticatedAdminAssistantRouteImport } from './routes/_authenticated/admin.assistant'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'
import { Route as ApiPublicHooksResetAdminPwRouteImport } from './routes/api/public/hooks/reset-admin-pw'
import { Route as ApiPublicHooksN8nInboundRouteImport } from './routes/api/public/hooks/n8n-inbound'
import { Route as ApiPublicHooksAutoSeoRouteImport } from './routes/api/public/hooks/auto-seo'
import { Route as AuthenticatedAdminLegalPreviewSlugRouteImport } from './routes/_authenticated/admin.legal.preview.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEnDotxmlRoute = SitemapEnDotxmlRouteImport.update({
  id: '/sitemap-en.xml',
  path: '/sitemap-en.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapArDotxmlRoute = SitemapArDotxmlRouteImport.update({
  id: '/sitemap-ar.xml',
  path: '/sitemap-ar.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const GovernoratesSlugRoute = GovernoratesSlugRouteImport.update({
  id: '/governorates/$slug',
  path: '/governorates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsSlugRoute = DownloadsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DownloadsRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PreviewPagesSlugRoute = PreviewPagesSlugRouteImport.update({
  id: '/preview/pages/$slug',
  path: '/preview/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewKnowledgeSlugRoute = PreviewKnowledgeSlugRouteImport.update({
  id: '/preview/knowledge/$slug',
  path: '/preview/knowledge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTranslationsRoute =
  AuthenticatedAdminTranslationsRouteImport.update({
    id: '/translations',
    path: '/translations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSocialCacheRoute =
  AuthenticatedAdminSocialCacheRouteImport.update({
    id: '/social-cache',
    path: '/social-cache',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsKeysRoute =
  AuthenticatedAdminSettingsKeysRouteImport.update({
    id: '/settings-keys',
    path: '/settings-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQaReportsRoute =
  AuthenticatedAdminQaReportsRouteImport.update({
    id: '/qa-reports',
    path: '/qa-reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLegalRoute = AuthenticatedAdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKpiRoute = AuthenticatedAdminKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHeroSlidesRoute =
  AuthenticatedAdminHeroSlidesRouteImport.update({
    id: '/hero-slides',
    path: '/hero-slides',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGovernoratesRoute =
  AuthenticatedAdminGovernoratesRouteImport.update({
    id: '/governorates',
    path: '/governorates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDownloadsAnalyticsRoute =
  AuthenticatedAdminDownloadsAnalyticsRouteImport.update({
    id: '/downloads-analytics',
    path: '/downloads-analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDownloadsRoute =
  AuthenticatedAdminDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDownloadLeadsRoute =
  AuthenticatedAdminDownloadLeadsRouteImport.update({
    id: '/download-leads',
    path: '/download-leads',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCareersRoute =
  AuthenticatedAdminCareersRouteImport.update({
    id: '/careers',
    path: '/careers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssistantRoute =
  AuthenticatedAdminAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicHooksResetAdminPwRoute =
  ApiPublicHooksResetAdminPwRouteImport.update({
    id: '/api/public/hooks/reset-admin-pw',
    path: '/api/public/hooks/reset-admin-pw',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksN8nInboundRoute =
  ApiPublicHooksN8nInboundRouteImport.update({
    id: '/api/public/hooks/n8n-inbound',
    path: '/api/public/hooks/n8n-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoSeoRoute = ApiPublicHooksAutoSeoRouteImport.update({
  id: '/api/public/hooks/auto-seo',
  path: '/api/public/hooks/auto-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminLegalPreviewSlugRoute =
  AuthenticatedAdminLegalPreviewSlugRouteImport.update({
    id: '/preview/$slug',
    path: '/preview/$slug',
    getParentRoute: () => AuthenticatedAdminLegalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRouteWithChildren
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap-ar.xml': typeof SitemapArDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/downloads/$slug': typeof DownloadsSlugRoute
  '/governorates/$slug': typeof GovernoratesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/assistant': typeof AuthenticatedAdminAssistantRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/careers': typeof AuthenticatedAdminCareersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/download-leads': typeof AuthenticatedAdminDownloadLeadsRoute
  '/admin/downloads': typeof AuthenticatedAdminDownloadsRoute
  '/admin/downloads-analytics': typeof AuthenticatedAdminDownloadsAnalyticsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/governorates': typeof AuthenticatedAdminGovernoratesRoute
  '/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/kpi': typeof AuthenticatedAdminKpiRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/legal': typeof AuthenticatedAdminLegalRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/qa-reports': typeof AuthenticatedAdminQaReportsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/settings-keys': typeof AuthenticatedAdminSettingsKeysRoute
  '/admin/social-cache': typeof AuthenticatedAdminSocialCacheRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/translations': typeof AuthenticatedAdminTranslationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/preview/knowledge/$slug': typeof PreviewKnowledgeSlugRoute
  '/preview/pages/$slug': typeof PreviewPagesSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/auto-seo': typeof ApiPublicHooksAutoSeoRoute
  '/api/public/hooks/n8n-inbound': typeof ApiPublicHooksN8nInboundRoute
  '/api/public/hooks/reset-admin-pw': typeof ApiPublicHooksResetAdminPwRoute
  '/admin/legal/preview/$slug': typeof AuthenticatedAdminLegalPreviewSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRouteWithChildren
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/sitemap-ar.xml': typeof SitemapArDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/downloads/$slug': typeof DownloadsSlugRoute
  '/governorates/$slug': typeof GovernoratesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/products': typeof ProductsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/assistant': typeof AuthenticatedAdminAssistantRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/careers': typeof AuthenticatedAdminCareersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/download-leads': typeof AuthenticatedAdminDownloadLeadsRoute
  '/admin/downloads': typeof AuthenticatedAdminDownloadsRoute
  '/admin/downloads-analytics': typeof AuthenticatedAdminDownloadsAnalyticsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/governorates': typeof AuthenticatedAdminGovernoratesRoute
  '/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/kpi': typeof AuthenticatedAdminKpiRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/legal': typeof AuthenticatedAdminLegalRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/qa-reports': typeof AuthenticatedAdminQaReportsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/settings-keys': typeof AuthenticatedAdminSettingsKeysRoute
  '/admin/social-cache': typeof AuthenticatedAdminSocialCacheRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/translations': typeof AuthenticatedAdminTranslationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/preview/knowledge/$slug': typeof PreviewKnowledgeSlugRoute
  '/preview/pages/$slug': typeof PreviewPagesSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/auto-seo': typeof ApiPublicHooksAutoSeoRoute
  '/api/public/hooks/n8n-inbound': typeof ApiPublicHooksN8nInboundRoute
  '/api/public/hooks/reset-admin-pw': typeof ApiPublicHooksResetAdminPwRoute
  '/admin/legal/preview/$slug': typeof AuthenticatedAdminLegalPreviewSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRouteWithChildren
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap-ar.xml': typeof SitemapArDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/downloads/$slug': typeof DownloadsSlugRoute
  '/governorates/$slug': typeof GovernoratesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/assistant': typeof AuthenticatedAdminAssistantRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/careers': typeof AuthenticatedAdminCareersRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/download-leads': typeof AuthenticatedAdminDownloadLeadsRoute
  '/_authenticated/admin/downloads': typeof AuthenticatedAdminDownloadsRoute
  '/_authenticated/admin/downloads-analytics': typeof AuthenticatedAdminDownloadsAnalyticsRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/governorates': typeof AuthenticatedAdminGovernoratesRoute
  '/_authenticated/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/kpi': typeof AuthenticatedAdminKpiRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/legal': typeof AuthenticatedAdminLegalRouteWithChildren
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/qa-reports': typeof AuthenticatedAdminQaReportsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/settings-keys': typeof AuthenticatedAdminSettingsKeysRoute
  '/_authenticated/admin/social-cache': typeof AuthenticatedAdminSocialCacheRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/translations': typeof AuthenticatedAdminTranslationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/preview/knowledge/$slug': typeof PreviewKnowledgeSlugRoute
  '/preview/pages/$slug': typeof PreviewPagesSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/auto-seo': typeof ApiPublicHooksAutoSeoRoute
  '/api/public/hooks/n8n-inbound': typeof ApiPublicHooksN8nInboundRoute
  '/api/public/hooks/reset-admin-pw': typeof ApiPublicHooksResetAdminPwRoute
  '/_authenticated/admin/legal/preview/$slug': typeof AuthenticatedAdminLegalPreviewSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/certificates'
    | '/clients'
    | '/contact'
    | '/downloads'
    | '/faq'
    | '/gallery'
    | '/knowledge'
    | '/privacy'
    | '/products'
    | '/projects'
    | '/quote'
    | '/services'
    | '/sitemap-ar.xml'
    | '/sitemap-en.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/downloads/$slug'
    | '/governorates/$slug'
    | '/knowledge/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/knowledge/'
    | '/products/'
    | '/projects/'
    | '/services/'
    | '/admin/about'
    | '/admin/ai'
    | '/admin/applications'
    | '/admin/assistant'
    | '/admin/audit-logs'
    | '/admin/blog'
    | '/admin/careers'
    | '/admin/categories'
    | '/admin/certificates'
    | '/admin/clients'
    | '/admin/download-leads'
    | '/admin/downloads'
    | '/admin/downloads-analytics'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/governorates'
    | '/admin/hero-slides'
    | '/admin/integrations'
    | '/admin/kpi'
    | '/admin/leads'
    | '/admin/legal'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/qa-reports'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/settings-keys'
    | '/admin/social-cache'
    | '/admin/testimonials'
    | '/admin/translations'
    | '/admin/users'
    | '/preview/knowledge/$slug'
    | '/preview/pages/$slug'
    | '/admin/'
    | '/api/public/hooks/auto-seo'
    | '/api/public/hooks/n8n-inbound'
    | '/api/public/hooks/reset-admin-pw'
    | '/admin/legal/preview/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/certificates'
    | '/clients'
    | '/contact'
    | '/downloads'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/quote'
    | '/sitemap-ar.xml'
    | '/sitemap-en.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/downloads/$slug'
    | '/governorates/$slug'
    | '/knowledge/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/knowledge'
    | '/products'
    | '/projects'
    | '/services'
    | '/admin/about'
    | '/admin/ai'
    | '/admin/applications'
    | '/admin/assistant'
    | '/admin/audit-logs'
    | '/admin/blog'
    | '/admin/careers'
    | '/admin/categories'
    | '/admin/certificates'
    | '/admin/clients'
    | '/admin/download-leads'
    | '/admin/downloads'
    | '/admin/downloads-analytics'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/governorates'
    | '/admin/hero-slides'
    | '/admin/integrations'
    | '/admin/kpi'
    | '/admin/leads'
    | '/admin/legal'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/qa-reports'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/settings-keys'
    | '/admin/social-cache'
    | '/admin/testimonials'
    | '/admin/translations'
    | '/admin/users'
    | '/preview/knowledge/$slug'
    | '/preview/pages/$slug'
    | '/admin'
    | '/api/public/hooks/auto-seo'
    | '/api/public/hooks/n8n-inbound'
    | '/api/public/hooks/reset-admin-pw'
    | '/admin/legal/preview/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/careers'
    | '/certificates'
    | '/clients'
    | '/contact'
    | '/downloads'
    | '/faq'
    | '/gallery'
    | '/knowledge'
    | '/privacy'
    | '/products'
    | '/projects'
    | '/quote'
    | '/services'
    | '/sitemap-ar.xml'
    | '/sitemap-en.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/downloads/$slug'
    | '/governorates/$slug'
    | '/knowledge/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/knowledge/'
    | '/products/'
    | '/projects/'
    | '/services/'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/assistant'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/careers'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/download-leads'
    | '/_authenticated/admin/downloads'
    | '/_authenticated/admin/downloads-analytics'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/governorates'
    | '/_authenticated/admin/hero-slides'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/kpi'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/legal'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/qa-reports'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/settings-keys'
    | '/_authenticated/admin/social-cache'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/translations'
    | '/_authenticated/admin/users'
    | '/preview/knowledge/$slug'
    | '/preview/pages/$slug'
    | '/_authenticated/admin/'
    | '/api/public/hooks/auto-seo'
    | '/api/public/hooks/n8n-inbound'
    | '/api/public/hooks/reset-admin-pw'
    | '/_authenticated/admin/legal/preview/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  CertificatesRoute: typeof CertificatesRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRouteWithChildren
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapArDotxmlRoute: typeof SitemapArDotxmlRoute
  SitemapEnDotxmlRoute: typeof SitemapEnDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  GovernoratesSlugRoute: typeof GovernoratesSlugRoute
  PreviewKnowledgeSlugRoute: typeof PreviewKnowledgeSlugRoute
  PreviewPagesSlugRoute: typeof PreviewPagesSlugRoute
  ApiPublicHooksAutoSeoRoute: typeof ApiPublicHooksAutoSeoRoute
  ApiPublicHooksN8nInboundRoute: typeof ApiPublicHooksN8nInboundRoute
  ApiPublicHooksResetAdminPwRoute: typeof ApiPublicHooksResetAdminPwRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-en.xml': {
      id: '/sitemap-en.xml'
      path: '/sitemap-en.xml'
      fullPath: '/sitemap-en.xml'
      preLoaderRoute: typeof SitemapEnDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-ar.xml': {
      id: '/sitemap-ar.xml'
      path: '/sitemap-ar.xml'
      fullPath: '/sitemap-ar.xml'
      preLoaderRoute: typeof SitemapArDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/governorates/$slug': {
      id: '/governorates/$slug'
      path: '/governorates/$slug'
      fullPath: '/governorates/$slug'
      preLoaderRoute: typeof GovernoratesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/$slug': {
      id: '/downloads/$slug'
      path: '/$slug'
      fullPath: '/downloads/$slug'
      preLoaderRoute: typeof DownloadsSlugRouteImport
      parentRoute: typeof DownloadsRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/preview/pages/$slug': {
      id: '/preview/pages/$slug'
      path: '/preview/pages/$slug'
      fullPath: '/preview/pages/$slug'
      preLoaderRoute: typeof PreviewPagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/knowledge/$slug': {
      id: '/preview/knowledge/$slug'
      path: '/preview/knowledge/$slug'
      fullPath: '/preview/knowledge/$slug'
      preLoaderRoute: typeof PreviewKnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/translations': {
      id: '/_authenticated/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AuthenticatedAdminTranslationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/social-cache': {
      id: '/_authenticated/admin/social-cache'
      path: '/social-cache'
      fullPath: '/admin/social-cache'
      preLoaderRoute: typeof AuthenticatedAdminSocialCacheRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings-keys': {
      id: '/_authenticated/admin/settings-keys'
      path: '/settings-keys'
      fullPath: '/admin/settings-keys'
      preLoaderRoute: typeof AuthenticatedAdminSettingsKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qa-reports': {
      id: '/_authenticated/admin/qa-reports'
      path: '/qa-reports'
      fullPath: '/admin/qa-reports'
      preLoaderRoute: typeof AuthenticatedAdminQaReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/legal': {
      id: '/_authenticated/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AuthenticatedAdminLegalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kpi': {
      id: '/_authenticated/admin/kpi'
      path: '/kpi'
      fullPath: '/admin/kpi'
      preLoaderRoute: typeof AuthenticatedAdminKpiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hero-slides': {
      id: '/_authenticated/admin/hero-slides'
      path: '/hero-slides'
      fullPath: '/admin/hero-slides'
      preLoaderRoute: typeof AuthenticatedAdminHeroSlidesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/governorates': {
      id: '/_authenticated/admin/governorates'
      path: '/governorates'
      fullPath: '/admin/governorates'
      preLoaderRoute: typeof AuthenticatedAdminGovernoratesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/downloads-analytics': {
      id: '/_authenticated/admin/downloads-analytics'
      path: '/downloads-analytics'
      fullPath: '/admin/downloads-analytics'
      preLoaderRoute: typeof AuthenticatedAdminDownloadsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/downloads': {
      id: '/_authenticated/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AuthenticatedAdminDownloadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/download-leads': {
      id: '/_authenticated/admin/download-leads'
      path: '/download-leads'
      fullPath: '/admin/download-leads'
      preLoaderRoute: typeof AuthenticatedAdminDownloadLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/careers': {
      id: '/_authenticated/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AuthenticatedAdminCareersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assistant': {
      id: '/_authenticated/admin/assistant'
      path: '/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AuthenticatedAdminAssistantRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/reset-admin-pw': {
      id: '/api/public/hooks/reset-admin-pw'
      path: '/api/public/hooks/reset-admin-pw'
      fullPath: '/api/public/hooks/reset-admin-pw'
      preLoaderRoute: typeof ApiPublicHooksResetAdminPwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/n8n-inbound': {
      id: '/api/public/hooks/n8n-inbound'
      path: '/api/public/hooks/n8n-inbound'
      fullPath: '/api/public/hooks/n8n-inbound'
      preLoaderRoute: typeof ApiPublicHooksN8nInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-seo': {
      id: '/api/public/hooks/auto-seo'
      path: '/api/public/hooks/auto-seo'
      fullPath: '/api/public/hooks/auto-seo'
      preLoaderRoute: typeof ApiPublicHooksAutoSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/legal/preview/$slug': {
      id: '/_authenticated/admin/legal/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/admin/legal/preview/$slug'
      preLoaderRoute: typeof AuthenticatedAdminLegalPreviewSlugRouteImport
      parentRoute: typeof AuthenticatedAdminLegalRoute
    }
  }
}

interface AuthenticatedAdminLegalRouteChildren {
  AuthenticatedAdminLegalPreviewSlugRoute: typeof AuthenticatedAdminLegalPreviewSlugRoute
}

const AuthenticatedAdminLegalRouteChildren: AuthenticatedAdminLegalRouteChildren =
  {
    AuthenticatedAdminLegalPreviewSlugRoute:
      AuthenticatedAdminLegalPreviewSlugRoute,
  }

const AuthenticatedAdminLegalRouteWithChildren =
  AuthenticatedAdminLegalRoute._addFileChildren(
    AuthenticatedAdminLegalRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminAssistantRoute: typeof AuthenticatedAdminAssistantRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCareersRoute: typeof AuthenticatedAdminCareersRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminDownloadLeadsRoute: typeof AuthenticatedAdminDownloadLeadsRoute
  AuthenticatedAdminDownloadsRoute: typeof AuthenticatedAdminDownloadsRoute
  AuthenticatedAdminDownloadsAnalyticsRoute: typeof AuthenticatedAdminDownloadsAnalyticsRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminGovernoratesRoute: typeof AuthenticatedAdminGovernoratesRoute
  AuthenticatedAdminHeroSlidesRoute: typeof AuthenticatedAdminHeroSlidesRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminKpiRoute: typeof AuthenticatedAdminKpiRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminLegalRoute: typeof AuthenticatedAdminLegalRouteWithChildren
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminQaReportsRoute: typeof AuthenticatedAdminQaReportsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSettingsKeysRoute: typeof AuthenticatedAdminSettingsKeysRoute
  AuthenticatedAdminSocialCacheRoute: typeof AuthenticatedAdminSocialCacheRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTranslationsRoute: typeof AuthenticatedAdminTranslationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminAssistantRoute: AuthenticatedAdminAssistantRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCareersRoute: AuthenticatedAdminCareersRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminDownloadLeadsRoute: AuthenticatedAdminDownloadLeadsRoute,
  AuthenticatedAdminDownloadsRoute: AuthenticatedAdminDownloadsRoute,
  AuthenticatedAdminDownloadsAnalyticsRoute:
    AuthenticatedAdminDownloadsAnalyticsRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminGovernoratesRoute: AuthenticatedAdminGovernoratesRoute,
  AuthenticatedAdminHeroSlidesRoute: AuthenticatedAdminHeroSlidesRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminKpiRoute: AuthenticatedAdminKpiRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminLegalRoute: AuthenticatedAdminLegalRouteWithChildren,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminQaReportsRoute: AuthenticatedAdminQaReportsRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSettingsKeysRoute: AuthenticatedAdminSettingsKeysRoute,
  AuthenticatedAdminSocialCacheRoute: AuthenticatedAdminSocialCacheRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminTranslationsRoute: AuthenticatedAdminTranslationsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DownloadsRouteChildren {
  DownloadsSlugRoute: typeof DownloadsSlugRoute
}

const DownloadsRouteChildren: DownloadsRouteChildren = {
  DownloadsSlugRoute: DownloadsSlugRoute,
}

const DownloadsRouteWithChildren = DownloadsRoute._addFileChildren(
  DownloadsRouteChildren,
)

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  CertificatesRoute: CertificatesRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRouteWithChildren,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapArDotxmlRoute: SitemapArDotxmlRoute,
  SitemapEnDotxmlRoute: SitemapEnDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  GovernoratesSlugRoute: GovernoratesSlugRoute,
  PreviewKnowledgeSlugRoute: PreviewKnowledgeSlugRoute,
  PreviewPagesSlugRoute: PreviewPagesSlugRoute,
  ApiPublicHooksAutoSeoRoute: ApiPublicHooksAutoSeoRoute,
  ApiPublicHooksN8nInboundRoute: ApiPublicHooksN8nInboundRoute,
  ApiPublicHooksResetAdminPwRoute: ApiPublicHooksResetAdminPwRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
